version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=simple-secret-key
  admin:
    build: ./admin
    ports:
      - "3000:80"
  public:
    build: ./public
    ports:
      - "3001:80"
